Agrego script de creacion de la base de datos
UTN-FRSF-TPS/DIED-STM pull request #7
Opened 2021-07-14 12:56 UTC by vFontana0

Se agregó el script de creación de la base de datos (bd.sql)

2021-07-15 14:31 UTC, irina556 approved these changes

2021-07-15 18:23 UTC, Patacon13 commented
capaz en lugar de color un atributo red, green, blue?

2021-07-15 23:58 UTC, Patacon13 requested changes
No estoy seguro, pero manejar los horarios como time o algo así no facilitará la integración? (https://www.postgresql.org/docs/9.1/datatype-datetime.html) digo por horario_apertura y horario_cierre

2021-07-16 00:01 UTC, vFontana0 commented
> No estoy seguro, pero manejar los horarios como time o algo así no facilitará la integración? (https://www.postgresql.org/docs/9.1/datatype-datetime.html) digo por horario_apertura y horario_cierre

Buenas, considero que varchar es un tipo de dato muy versatil y se adapta perfectamente

2021-07-16 00:04 UTC, Patacon13 commented
Buenas, pero hay que recorrerlo 😱😔😔😔

> > No estoy seguro, pero manejar los horarios como time o algo así no facilitará la integración? (https://www.postgresql.org/docs/9.1/datatype-datetime.html) digo por horario_apertura y horario_cierre
> 
> Buenas, considero que varchar es un tipo de dato muy versatil y se adapta perfectamente

2021-07-16 00:05 UTC, Patacon13 approved these changes
suena bien!

2021-07-16 00:06 UTC, merged